# PyInstaller spec for building a standalone JAMES executable (no Python required).
# Usage:  pyinstaller james.spec --noconfirm
import sys

block_cipher = None

a = Analysis(
    ["packaging/entry.py"],
    pathex=["."],
    binaries=[],
    datas=[
        ("james/ui/web", "james/ui/web"),
        (".env.example", "."),
    ],
    hiddenimports=[
        "james.config",
        "james.updater",
        "james.evaluation",
        "james.evaluation.worker",
        "james.llm.base",
        "james.llm.factory",
        "james.llm.providers",
        "james.core.agent",
        "james.core.assistant",
        "james.core.command_policy",
        "james.core.computeruse",
        "james.core.doctor",
        "james.core.guard",
        "james.core.isolation",
        "james.core.personality",
        "james.core.recipes",
        "james.core.scheduler",
        "james.core.secrets",
        "james.gateway",
        "james.gateway.base",
        "james.gateway.discord",
        "james.gateway.manager",
        "james.gateway.slack",
        "james.gateway.telegram",
        "james.gateway.whatsapp",
        "james.integrations",
        "james.integrations.catalog",
        "james.integrations.manager",
        "james.ui.dashboard",
        "james.ui.server",
        "james.ui.shell",
        "james.voice.stt",
        "james.voice.tts",
        "james.tools.base",
        "james.tools.registry",
        "james.tools.background_tools",
        "james.tools.browser_tools",
        "james.tools.compute_tools",
        "james.tools.delegate_tool",
        "james.tools.desktop_tools",
        "james.tools.document_tools",
        "james.tools.file_manager_tools",
        "james.tools.file_tools",
        "james.tools.forge_tools",
        "james.tools.gateway_tools",
        "james.tools.marketplace",
        "james.tools.mcp_tools",
        "james.tools.memory_tools",
        "james.tools.office_tools",
        "james.tools.plugin_proxy",
        "james.tools.recipes_tools",
        "james.tools.research_tools",
        "james.tools.scheduler_tools",
        "james.tools.system_tools",
        "james.tools.web_tools",
        "rich",
        "requests",
        "urllib3",
        "dotenv",
        "uvicorn",
        "fastapi",
    ],
    cipher=block_cipher,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    name="JAMES",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    version="packaging/windows/version_info.txt",
)

# macOS: wrap the executable in a proper .app bundle (no-op elsewhere).
if sys.platform == "darwin":
    app = BUNDLE(
        exe,
        name="JAMES.app",
        icon=None,
        bundle_identifier="ai.james.assistant",
        version="1.0.0",
        info_plist={
            "NSHighResolutionCapable": True,
            "LSMinimumSystemVersion": "11.0",
            "NSMicrophoneUsageDescription": "JAMES listens for voice input.",
            "NSSpeechRecognitionUsageDescription": "JAMES transcribes voice input.",
        },
    )
