# PyInstaller spec for building a standalone JAMES executable (no Python required).
# Usage:  pyinstaller james.spec
block_cipher = None

a = Analysis(
    ["james/__main__.py"],
    pathex=["."],
    binaries=[],
    datas=[
        ("james/tools/marketplace", "james/tools/marketplace"),
        ("james/ui/web", "james/ui/web"),
        (".env.example", "."),
    ],
    hiddenimports=[
        "james.config",
        "james.evaluation",
        "james.llm.base",
        "james.llm.factory",
        "james.llm.providers",
        "james.core.agent",
        "james.core.assistant",
        "james.core.command_policy",
        "james.core.computeruse",
        "james.core.doctor",
        "james.core.guard",
        "james.core.personality",
        "james.core.scheduler",
        "james.core.secrets",
        "james.ui.dashboard",
        "james.ui.server",
        "james.ui.shell",
        "james.voice.stt",
        "james.voice.tts",
        "james.tools.base",
        "james.tools.registry",
        "james.tools.background_tools",
        "james.tools.browser_tools",
        "james.tools.delegate_tool",
        "james.tools.desktop_tools",
        "james.tools.document_tools",
        "james.tools.file_manager_tools",
        "james.tools.file_tools",
        "james.tools.forge_tools",
        "james.tools.marketplace",
        "james.tools.mcp_tools",
        "james.tools.memory_tools",
        "james.tools.research_tools",
        "james.tools.scheduler_tools",
        "james.tools.system_tools",
        "james.tools.web_tools",
        "rich",
        "requests",
        "urllib3",
        "dotenv",
    ],
    cipher=block_cipher,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    name="JAMES",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
)
