# PyInstaller spec for building a standalone JAMES executable (no Python required).
# Usage:  pyinstaller james.spec
import os

block_cipher = None

a = Analysis(
    ["james/__main__.py"],
    pathex=["."],
    binaries=[],
    datas=[
        ("james/tools", "james/tools"),
        ("james/plugins", "james/plugins"),
        (".env.example", "."),
    ],
    hiddenimports=[
        "james.llm.providers",
        "james.tools.browser_tools",
        "james.tools.memory_tools",
        "james.tools.scheduler_tools",
        "james.tools.system_tools",
        "james.tools.forge_tools",
        "james.tools.mcp_tools",
        "james.tools.file_tools",
        "james.tools.file_manager_tools",
        "james.tools.background_tools",
        "james.tools.research_tools",
        "james.tools.web_tools",
        "james.tools.document_tools",
        "james.tools.delegate_tool",
        "james.tools.base",
        "james.tools.registry",
        "james.core.guard",
        "james.core.scheduler",
        "james.core.agent",
        "james.core.assistant",
        "james.core.personality",
        "james.core.doctor",
        "james.config",
        "james.ui.orb",
        "james.ui.dashboard",
        "james.voice.stt",
        "james.voice.tts",
        "james.evaluation",
        "james.plugins",
        "playwright",
        "playwright.sync_api",
        "docx",
        "pptx",
        "reportlab",
        "fpdf2",
        "pyautogui",
        "pyperclip",
        "psutil",
        "plyer",
        "speech_recognition",
        "pyttsx3",
        "whisper",
        "edge_tts",
        "openai",
        "anthropic",
        "google.generativeai",
        "dotenv",
        "rich",
        "PyQt5",
        "PyQt5.QtCore",
        "PyQt5.QtGui",
        "PyQt5.QtWidgets",
        "mcp",
        "mcp.client.stdio",
        "mcp.client.streamable_http",
        "mcp.client.sse",
        "urllib3",
        "requests",
        "urllib.request",
        "sentence_transformers",
        "numpy",
    ],
    cipher=block_cipher,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    name="JAMES",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
)
