"""First-run onboarding: guide a new user from a bare checkout to a working .env.

Runs interactively when no ``.env`` exists (or via ``python -m james --setup``).
It never writes secrets to the repo — only to ``.env``, which is gitignored.

Express flow: paste an API key and JAMES detects the provider from its format,
so a typical setup is just "paste key -> Enter -> Enter".
"""

from __future__ import annotations

import os
from contextlib import suppress
from pathlib import Path

from .config import PROJECT_ROOT
from .llm.catalog import DEFAULT_MODELS, PROVIDER_KEY, PROVIDERS


def env_exists() -> bool:
    return (PROJECT_ROOT / ".env").exists()


def detect_provider(api_key: str) -> str | None:
    """Guess the provider from an API key's format, or None if unrecognized."""
    key = (api_key or "").strip()
    if not key:
        return None
    lowered = key.lower()
    if lowered.startswith("sk-ant-"):
        return "anthropic"
    if lowered.startswith("aiz"):
        return "gemini"
    if lowered.startswith("gsk_"):
        return "groq"
    if lowered.startswith("sk-or-"):
        return "openrouter"
    if lowered.startswith("sk-"):
        return "openai"
    # Mistral/DeepSeek/xAI/Together/Cerebras/Cohere keys have no universal
    # prefix, so they can't be detected reliably — fall through to manual.
    return None


def _ask(prompt: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    try:
        value = input(f"{prompt}{suffix}: ").strip()
    except (EOFError, KeyboardInterrupt):
        raise SystemExit(0) from None
    return value or default


def _choose_provider() -> str:
    print("\nWhich LLM provider do you want to use?")
    for i, name in enumerate(PROVIDERS, 1):
        print(f"  {i}. {name}")
    try:
        raw = input(f"Choice (1-{len(PROVIDERS)}) [{PROVIDERS[0]}]: ").strip()
    except (EOFError, KeyboardInterrupt):
        raise SystemExit(0) from None
    if not raw:
        return PROVIDERS[0]
    if raw.isdigit() and 1 <= int(raw) <= len(PROVIDERS):
        return PROVIDERS[int(raw) - 1]
    if raw.lower() in PROVIDERS:
        return raw.lower()
    print(f"Unknown provider '{raw}', defaulting to {PROVIDERS[0]}.")
    return PROVIDERS[0]


def run_onboarding(force: bool = False) -> Path:
    """Interactive wizard. Returns the path to the generated .env file.

    Express flow (recommended): paste an API key — JAMES detects the provider
    and offers its default model, so you only answer "Enter" a couple of times.
    If the key format isn't recognized (or you want a local model), the wizard
    falls back to the provider menu.

    ``force=True`` (used by ``--setup``) re-runs even if ``.env`` exists so
    users can switch providers; the first-run auto-trigger calls with
    ``force=False`` and is skipped when ``.env`` is already present.
    """
    from .core.assistant import get_logger

    log = get_logger()
    env_path = PROJECT_ROOT / ".env"
    if env_exists() and not force:
        log.info(".env already exists — skipping onboarding.")
        return env_path

    print("\n" + "=" * 60)
    print("  Welcome to JAMES — your open-source, voice-first JARVIS.")
    print("  Setup takes a few seconds. Press Enter to accept defaults.")
    print("=" * 60)

    provider, base_url, model, api_key = _prompt_credentials()

    voice = _ask("Enable voice mode? (y/n)", "n").lower() in ("y", "yes", "1", "true")

    lines = [
        "# Generated by `james --setup`",
        f"LLM_PROVIDER={provider}",
        f"LLM_MODEL={model}",
    ]
    if base_url:
        lines.append(f"CUSTOM_BASE_URL={base_url}")
    lines.append(f"{PROVIDER_KEY[provider]}={api_key}")
    lines.append("")
    lines.append("# Voice / speech")
    lines.append(f"VOICE_ENABLED={'true' if voice else 'false'}")
    if not voice:
        lines.append("STT_PROVIDER=none")
    lines.append("")
    lines.append("# Workspace & safety defaults")
    lines.append("WORKSPACE_DIR=./workspace")
    lines.append("JAMES_MODE=standard")
    lines.append("CONFIRM_DANGEROUS_ACTIONS=true")

    env_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    with suppress(Exception):
        os.chmod(env_path, 0o600)

    print("\n" + "=" * 60)
    print(f"  [OK] Created {env_path}")
    if api_key and not base_url:
        print("  [OK] API key saved (file is gitignored + chmod 600)")
    print("  Next: run `james` for the desktop app, or `james --text` for the CLI.")
    print("=" * 60)
    return env_path


def _prompt_credentials() -> tuple[str, str, str, str]:
    """Gather provider, base URL, model, and API key from the user.

    Returns ``(provider, base_url, model, api_key)``.
    """
    api_key = _ask("Paste your API key (or Enter to choose provider manually)")
    detected = detect_provider(api_key)
    if detected:
        default_model = DEFAULT_MODELS[detected]
        print(f"  • Detected provider: {detected}")
        provider = _ask("Provider", detected).lower() or detected
        if provider not in PROVIDER_KEY:
            print(f"  Unknown provider '{provider}' — using the provider menu.")
            provider = _choose_provider()
        if provider == "custom":
            base_url = _ask("Local model base URL", "http://localhost:11434/v1")
            model = _ask("Model id", DEFAULT_MODELS["custom"])
            return provider, base_url, model, api_key
        model = _ask("Model", default_model) or default_model
        return provider, "", model, api_key

    if api_key:
        print("  Key format not recognized — choosing provider manually.")
    provider = _choose_provider()
    if provider == "custom":
        base_url = _ask("Local model base URL", "http://localhost:11434/v1")
        model = _ask("Model id", DEFAULT_MODELS["custom"])
        api_key = api_key or _ask("API key (blank for local servers like Ollama)")
        return provider, base_url, model, api_key

    model = _ask("Model", DEFAULT_MODELS[provider]) or DEFAULT_MODELS[provider]
    api_key = api_key or _ask(f"API key (create one at the {provider} console)")
    return provider, "", model, api_key


def setup_cmd() -> int:
    """CLI entry for `james --setup` (re-runs even if .env exists)."""
    run_onboarding(force=True)
    from .core.assistant import get_logger

    get_logger().info("Onboarding complete.")
    return 0
