"""First-run onboarding: guide a new user from a bare checkout to a working .env.

Runs interactively when no ``.env`` exists (or via ``python -m james --setup``).
It never writes secrets to the repo — only to ``.env``, which is gitignored.
"""
from __future__ import annotations

from pathlib import Path

from .config import PROJECT_ROOT

PROVIDERS = [
    "openai",
    "anthropic",
    "gemini",
    "openrouter",
    "groq",
    "mistral",
    "xai",
    "deepseek",
    "together",
    "cerebras",
    "cohere",
    "custom",
]

# env key used by each provider to hold the API token
_PROVIDER_KEY = {
    "openai": "OPENAI_API_KEY",
    "anthropic": "ANTHROPIC_API_KEY",
    "gemini": "GEMINI_API_KEY",
    "openrouter": "OPENROUTER_API_KEY",
    "groq": "GROQ_API_KEY",
    "mistral": "MISTRAL_API_KEY",
    "xai": "XAI_API_KEY",
    "deepseek": "DEEPSEEK_API_KEY",
    "together": "TOGETHER_API_KEY",
    "cerebras": "CEREBRAS_API_KEY",
    "cohere": "COHERE_API_KEY",
    "custom": "CUSTOM_API_KEY",
}

_DEFAULT_MODEL = {
    "openai": "gpt-4o-mini",
    "anthropic": "claude-3-5-sonnet-latest",
    "gemini": "gemini-2.0-flash",
    "openrouter": "deepseek/deepseek-chat",
    "groq": "llama-3.3-70b-versatile",
    "mistral": "mistral-large-latest",
    "xai": "grok-3",
    "deepseek": "deepseek-chat",
    "together": "meta-llama/Llama-3.3-70B-Instruct-Turbo",
    "cerebras": "llama-3.3-70b",
    "cohere": "command-r-plus",
    "custom": "local-model",
}


def env_exists() -> bool:
    return (PROJECT_ROOT / ".env").exists()


def _ask(prompt: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    try:
        value = input(f"{prompt}{suffix}: ").strip()
    except (EOFError, KeyboardInterrupt):
        raise SystemExit(0) from None
    return value or default


def _choose_provider() -> str:
    print("\nWhich LLM provider do you want to use?")
    for i, name in enumerate(PROVIDERS, 1):
        print(f"  {i}. {name}")
    try:
        raw = input(f"Choice (1-{len(PROVIDERS)}) [{PROVIDERS[0]}]: ").strip()
    except (EOFError, KeyboardInterrupt):
        raise SystemExit(0) from None
    if not raw:
        return PROVIDERS[0]
    if raw.isdigit() and 1 <= int(raw) <= len(PROVIDERS):
        return PROVIDERS[int(raw) - 1]
    if raw.lower() in PROVIDERS:
        return raw.lower()
    print(f"Unknown provider '{raw}', defaulting to {PROVIDERS[0]}.")
    return PROVIDERS[0]


def run_onboarding(force: bool = False) -> Path:
    """Interactive wizard. Returns the path to the generated .env file.

    ``force=True`` (used by ``--setup``) re-runs even if ``.env`` exists so
    users can switch providers; the first-run auto-trigger calls with
    ``force=False`` and is skipped when ``.env`` is already present.
    """
    from .core.assistant import get_logger

    log = get_logger()
    env_path = PROJECT_ROOT / ".env"
    if env_exists() and not force:
        log.info(".env already exists — skipping onboarding.")
        return env_path

    print("\n" + "=" * 60)
    print("  Welcome to JAMES — your open-source, voice-first JARVIS.")
    print("  Let's get you set up in about 30 seconds.")
    print("=" * 60)

    provider = _choose_provider()
    key_env = _PROVIDER_KEY[provider]
    default_model = _DEFAULT_MODEL[provider]

    if provider == "custom":
        base_url = _ask("Local model base URL", "http://localhost:11434/v1")
        model = _ask("Model id", default_model)
        api_key = _ask("API key (blank for local servers like Ollama)")
    else:
        base_url = ""
        model = _ask("Model", default_model)
        api_key = _ask("API key (create one at the provider's console)")

    voice = _ask("Enable voice mode? (y/n)", "n").lower() in ("y", "yes", "1", "true")

    lines = [
        "# Generated by `python -m james --setup`",
        f"LLM_PROVIDER={provider}",
        f"LLM_MODEL={model}",
    ]
    if base_url:
        lines.append(f"CUSTOM_BASE_URL={base_url}")
    lines.append(f"{key_env}={api_key}")
    lines.append("")
    lines.append("# Voice / speech")
    lines.append(f"VOICE_ENABLED={'true' if voice else 'false'}")
    if not voice:
        lines.append("STT_PROVIDER=none")
    lines.append("")
    lines.append("# Workspace & safety defaults")
    lines.append("WORKSPACE_DIR=./workspace")
    lines.append("JAMES_MODE=standard")
    lines.append("CONFIRM_DANGEROUS_ACTIONS=true")

    env_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    try:
        if hasattr(os := __import__("os"), "chmod"):
            os.chmod(env_path, 0o600)
    except Exception:
        pass

    print("\n" + "=" * 60)
    print(f"  [OK] Created {env_path}")
    if api_key and not base_url:
        print("  [OK] API key saved (file is gitignored + chmod 600)")
    print("  Next: run `python -m james` to start chatting.")
    print("=" * 60)
    return env_path


def setup_cmd() -> int:
    """CLI entry for `python -m james --setup` (re-runs even if .env exists)."""
    run_onboarding(force=True)
    from .core.assistant import get_logger

    get_logger().info("Onboarding complete.")
    return 0
